MODEL: 'CNN60d'

DATASET: 
  LOOKBACK_WIN: 60
  START_DATE: 20091231
  END_DATE: 20111231
  MODE: default
  INDICATORS: 
    # - NAME: MA
    # - PARAM: 60 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
#  PARALLEL_NUM: 32
  PARALLEL_NUM: -1


TRAIN:
  LABEL: RET5
  VALID_RATIO: 0.3
  # BATCH_SIZE: 128
  BATCH_SIZE: 64
  NEPOCH: 100
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I60R5_OHLCV/I60R5_OHLCV_09-11.tar
  LOG_SAVE_FILE: logs/I60R5_OHLCV/I60R5_OHLCV_09-11.csv
  EARLY_STOP_EPOCH: 4

TEST:
  START_DATE: 20111231
  END_DATE: 20121231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I60R5_OHLCV/I60R5_OHLCV_11-12.csv
