name: temp
dataset: 
  lookback_win_size: 5
  start_date: 20091231
  end_data: 20111231
  mode: 'train'
  indicators: {'MA':[20]}
  show_volume: True

skill:
  name1: coding
  time: 2years
job:
  - name2: JD
    pay: 2k
  - name3: HW
    pay: 4k