MODEL: 'CNN5d'

DATASET: 
  LOOKBACK_WIN: 5
  START_DATE: 20091231
  END_DATE: 20111231
  MODE: default
  INDICATORS: 
    - NAME: MA
    - PARAM: 5 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET5
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 200
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I5R5/I5R5_09-11.tar
  LOG_SAVE_FILE: logs/I5R5/I5R5_09-11.csv
  EARLY_STOP_EPOCH: 8

TEST:
  START_DATE: 20111231
  END_DATE: 20121231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I5R5/I5R5_11-12.csv