MODEL: 'CNN20d'

DATASET: 
  LOOKBACK_WIN: 20
  START_DATE: 20091231
  END_DATE: 20111231
  MODE: train
  INDICATORS: 
    - NAME: MA
    - PARAM: 20 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.1
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET20
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 200
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.001
  MODEL_SAVE_FILE: models/I20R20/I20R20_09-11.tar
  LOG_SAVE_FILE: logs/I20R20/I20R20_09-11.csv

