MODEL: 'CNN20d'

DATASET: 
  LOOKBACK_WIN: 20
  START_DATE: 19930101
  END_DATE: 20001231
  MODE: default
  INDICATORS: 
    # - NAME: MA
    # - PARAM: 20 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
#  PARALLEL_NUM: 32
  PARALLEL_NUM: -1


TRAIN:
  LABEL: RET20
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 100
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models_2/I20R20_OHLCV/I20R20_OHLCV_93-00_train.tar
  LOG_SAVE_FILE: logs_2/I20R20_OHLCV/I20R20_OHLCV_93-00_train.csv
  EARLY_STOP_EPOCH: 2

TEST:
  START_DATE: 20010101
  END_DATE: 20191231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I20R20_OHLCV/I20R20_OHLCV_01-19.csv
