MODEL: 'CNN20d'

DATASET: 
  LOOKBACK_WIN: 20
  START_DATE: 20111231
  END_DATE: 20131231
  MODE: default
  INDICATORS: 
    - NAME: MA
    - PARAM: 20 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET5
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 200
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I20R5/I20R5_11-13.tar
  LOG_SAVE_FILE: logs/I20R5/I20R5_11-13.csv
  EARLY_STOP_EPOCH: 16

TEST:
  START_DATE: 20131231
  END_DATE: 20141231