MODEL: 'CNN20d'

DATASET: 
  LOOKBACK_WIN: 20
  START_DATE: 20171231
  END_DATE: 20191231
  MODE: default
  INDICATORS: 
    - NAME: MA
    - PARAM: 20 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET5
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 200
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I20R5/I20R5_17-19.tar
  LOG_SAVE_FILE: logs/I20R5/I20R5_17-19.csv
  EARLY_STOP_EPOCH: 8

TEST:
  START_DATE: 20191231
  END_DATE: 20201231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I20R5/I20R5_19-20.csv